language:
- objective-c
env:
  matrix:
  - INSTALL_TYPE='system' VERSION=2.7
  - INSTALL_TYPE='homebrew' VERSION=2.7.9
  - INSTALL_TYPE='homebrew' VERSION=3.4.3
install:
- source terryfy/travis_tools.sh
- get_python_environment $INSTALL_TYPE $VERSION venv
- pip install wheel
- python setup.py bdist_wheel
- pip install dist/*.whl
script:
- python setup.py test
before_deploy:
- cd dist
- "whl_file=$(echo *.whl)"
deploy:
  provider: releases
  api_key:
    secure: SP/ebqpZV/f9cj7chBrA9XomQ8hMAHjJ1i1lwkxGsFEel3TdlcB/mlSAvvb2m/UerXnNjSRTXNoyvXZWRGN4LhRqsPxu+TrOs9LYbu1QVeZEAxikEJNaFuA/MXNDaL5cMLN9Gzmu1dBRqaEAgnI8/7o+bqrZGQlJ826PXagk7AI=
  file: $whl_file
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
