language:
- objective-c
env:
  matrix:
  - VERSION=2.7.9
  - VERSION=3.4.3
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install wheel
- python setup.py bdist_wheel
- pip install dist/*.whl
script:
- python setup.py test
- "whl_file=$(echo *.whl)"
deploy:
  provider: releases
  api_key:
    secure: "Hb2KUpbeeyTVs3RfUKcbV0fXfAblkvlRejIQBMPPKKHJlW/m+i9ckD3rWim2fxFABpBmaNxWGCCob1cnPt27py2WiurvWehidumD0tzhybQ067Zvn58AaNWtd6IDHOqrxOweia3u5QuhEpaUvQQsX+s1QqfZ/EVL2I5B7nJE1C8="
  file: $whl_file
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
