language:
- objective-c
env:
  matrix:
  - VERSION=2.7.9
  - VERSION=3.4.3
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install wheel
- python setup.py bdist_wheel
- pip install dist/*.whl
script:
- python setup.py test
- "whl_file=$(echo *.whl)"
deploy:
  provider: releases
  api_key: dabf8f304bfb5a8bcce0a955e2bd3ec90366fa71
  file: $whl_file
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
