language:
- objective-c
env:
  matrix:
  - VERSION=2.7.9
  - VERSION=3.4.3
install:
- source terryfy/travis_tools.sh
- git submodule update --init --recursive
- get_python_environment macpython $VERSION venv
- python setup.py bdist_wheel
- pip install dist/*.whl
script:
- python setup.py test
