language:
- objective-c
env:
  matrix:
  - VERSION=2.7.9
  - VERSION=3.4.3
install:
- source terryfy/travis_tools.sh
- get_python_environment homebrew $VERSION venv
- pip install wheel
- python setup.py bdist_wheel
- pip install dist/*.whl
script:
- python setup.py test
- "whl_file=$(echo *.whl)"
deploy:
  provider: releases
  api_key:
    secure: TaFmY+PSl4GzsWONsEOhNP+j3u62gxRmDdalZbkR1kedtnlfq8nKz3S2H8qYH1kO8AiADHxWD5Vsn6D4RV/avgmTt8Uqb71S5kXkK4wX2yTEIDmdj52MqCMQgWPoJNNr1N0FvZw1aDE38/Jkrw1gIBK5bz6LW1s7t7xqBhjlD7o=
  file: $whl_file
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
