environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    # - PYTHON: "C:\\Python33"
    #   PYTHON_VERSION: "3.3.5"
    #   PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"

    # - PYTHON: "C:\\Python33-x64"
    #   PYTHON_VERSION: "3.3.5"
    #   PYTHON_ARCH: "64"
    #   WINDOWS_SDK_VERSION: "v7.1"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"
  - "git submodule update --init --recursive"

build: off

# test_script:

after_test:
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel"
  - "%WITH_COMPILER% %PYTHON%/Scripts/pip install --upgrade -v --no-index --find-links=%CD%/dist Brotli"
  - "%WITH_COMPILER% %PYTHON%/python setup.py test"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse

deploy:
  - provider: GitHub
    auth_token:
      secure: o3NRzdcpPCSFjd9Gtwj9zjXP0yPRAieP0S0d4I8BK6/Xbl31u+9EsSiE+AUX8e2H
    artifact:
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true       # deploy on tag push only